Repository MegEngine/MegEngine, pull requests merged in 2022-09, with the labels that each got.

#397 update functional.batch_norm docstring
  imperative/python/megengine/functional/nn.py
Labels: status: in progress, type: documentation, merging

#441 docs(mge/functional): update functional.nn.max_pool2d docstring
  imperative/python/megengine/functional/nn.py
Labels: type: documentation, merging

#442 docs(mge/functional): update functional.nn.avg_pool2d docstring
  imperative/python/megengine/functional/nn.py
Labels: type: documentation, merging

#464 fix flops count bug for ConvTranspose2d
  imperative/python/megengine/utils/module_stats.py
Labels: merging

#478 docs(mge/functional): update copy example
  imperative/python/megengine/functional/tensor.py
Labels: merging
